# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1012, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.select_hex_file = QtWidgets.QPushButton(self.centralwidget)
        self.select_hex_file.setGeometry(QtCore.QRect(30, 40, 201, 51))
        self.select_hex_file.setObjectName("select_hex_file")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 130, 911, 361))
        self.textEdit.setObjectName("textEdit")
        self.create_bin2hash = QtWidgets.QPushButton(self.centralwidget)
        self.create_bin2hash.setGeometry(QtCore.QRect(250, 40, 201, 51))
        self.create_bin2hash.setObjectName("create_bin2hash")
        self.create_publickey = QtWidgets.QPushButton(self.centralwidget)
        self.create_publickey.setGeometry(QtCore.QRect(470, 40, 201, 51))
        self.create_publickey.setObjectName("create_publickey")
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(680, 40, 201, 51))
        self.clear.setObjectName("clear")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1012, 22))
        self.menubar.setObjectName("menubar")
        self.menuMainWindow = QtWidgets.QMenu(self.menubar)
        self.menuMainWindow.setObjectName("menuMainWindow")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuMainWindow.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.select_hex_file.setText(_translate("MainWindow", "请选择文件(hex)文件"))
        self.create_bin2hash.setText(_translate("MainWindow", "从bin文件生成hash"))
        self.create_publickey.setText(_translate("MainWindow", "随机生成公钥为"))
        self.clear.setText(_translate("MainWindow", "clear"))
        self.menuMainWindow.setTitle(_translate("MainWindow", "Signature"))





